services:
  opengate:
    container_name: opengate
    privileged: true
    restart: unless-stopped
    image: nguyentrantrung/opengate:latest
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # USB Coral
      - /dev/dri/renderD128:/dev/dri/renderD128 # Intel hardware acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/opengate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: host
