services:
  nginx:
    image: nginx:1.25.4
    container_name: opengate
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: 4
          memory: '4096M'
